---
- name: Deploy Flask App Locally
  hosts: localhost
  connection: local
  tasks:
    - name: Stop running container if any
      shell: docker stop flask-app || true && docker rm flask-app || true

    - name: Pull latest Docker image
      shell: docker pull priyanshubhatt80/flask-cicd:latest

    - name: Run container
      shell: docker run -d -p 5000:5000 --name flask-app priyanshubhatt80/flask-cicd:latest
